//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bileet15
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Population { get; set; }
        public decimal Square { get; set; }
        public int RegionId { get; set; }
        public string Picture { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
